### ISSUE TITLE
Unable to set `minLength` on property

### ISSUE THREAD

**Issue by Invis1ble** [Limenius/Liform#27]
My form contains `RepeatedType` of `PasswordType`:

```php
$builder
    ->add('plainPassword', RepeatedType::class, [
        'type' => PasswordType::class,
    ])
;
```

validation rules looks like this:

```yaml
plainPassword:
    - NotBlank: ~
    - Length:
        min: 6
        max: 255
```
so `ValidatorGuesser` can't guess length and `StringTransformer::addMinLength()` doesn't add `minLength`.

I would suggest to look at `attr.minlength` option like in `addMaxLength()` method and, if it not exists, run default algorithm of guessing by validation rules.
